/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'maheshrajannan' at '4/20/16 12:06 PM' with Gradle 2.12
 *
 * @author maheshrajannan, @date 4/20/16 12:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
